version: '3'

vars:
  IMAGE: toshy/lighthouse

env:
  UID:
    sh: id -u
  GID:
    sh: id -g
  DOCKER_COMPOSE_RUN: docker compose --progress quiet run --rm --build --remove-orphans

tasks:
  default:
    cmds:
      - task --list

  # Docker
  build:
    desc: Build local images
    vars:
      TARGETS: [ 'dev', 'prod' ]
    cmds:
      - for:
          var: TARGETS
        cmd: docker buildx build --load --target {{.ITEM}} --tag {{.IMAGE}}:{{.ITEM}} .

  down:
    desc: Down service
    cmds:
      - docker compose down {{.CLI_ARGS | default "--rmi local --remove-orphans"}}

  run:
    desc: Run service
    vars:
      DATA_DIRECTORY: '{{.o | default "data"}}'
    cmds:
      - mkdir -p $(dirname $PWD)/{{.DATA_DIRECTORY}}
      - $DOCKER_COMPOSE_RUN -u $(id -u):$(id -g) dev python -m lighthouse {{.CLI_ARGS}}

  # Development tools
  ruff:
    desc: Run ruff
    cmds:
      - $DOCKER_COMPOSE_RUN dev ruff check .

  ruff:fix:
    desc: Run ruff fix
    cmds:
      - $DOCKER_COMPOSE_RUN dev ruff check --fix .

  black:
    desc: Run black
    cmds:
      - $DOCKER_COMPOSE_RUN dev black . --check --diff --color

  black:fix:
    desc: Run black fix
    cmds:
      - $DOCKER_COMPOSE_RUN dev black .

  mypy:
    desc: Run mypy
    cmds:
      - $DOCKER_COMPOSE_RUN dev mypy .
