name: Lighthouse Unit Listing

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      pages: write
      id-token: write
    defaults:
      run:
        working-directory: backend
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup YQ
        uses: mikefarah/yq@v4.44.5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run script
        run: python -m lighthouse
        env:
          LOGURU_LEVEL: SUCCESS
          DATA_DIRECTORY: ../data

      - name: Commit changes
        id: auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: '*.json'
          commit_message: Update Lighthouse units listing

      - name: Create release
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: |
          tag=$(date +%Y.%m.%d)-$GITHUB_RUN_ID
          triggered_by="🤖"
          if [[ "${GITHUB_EVENT_NAME}" == "workflow_dispatch" ]]; then
            triggered_by="✍️"
          fi

          gh release create "$tag" --title="$tag $triggered_by" --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload pages artifact
        #if: steps.auto-commit-action.outputs.changes_detected == 'true'
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./data

      - name: Deploy to GitHub Pages
        #if: steps.auto-commit-action.outputs.changes_detected == 'true'
        id: deployment
        uses: actions/deploy-pages@v4
